

POST http://localhost:3005/docente
Content-Type: application/json

{
    "id_docente": 1,
    "nome": "tata" ,
    "email": "tatata@hotmail.com" ,
    "data_nasceu": "1982-12-23", 
    "id_turma": 1, 
    "especiallidades": "JS"
}